version: '3'
services:
  laravel.test:
    image: laravelsail/php83-composer
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:80 server.php

